CREATE TABLE comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipeid INTEGER REFERENCES recipes(id),
    userid INTEGER REFERENCES users(id),
    comment TEXT NOT NULL,
    imgurl TEXT NOT NULL
);