INSERT INTO ingredients (recipeid, title, amount)
VALUES
    (1, "flour", "1 cup"),
    (1, "eggs", "2"),
    (1, "baking soda", "1 tsp"),
    (1, "sugar", "1/3 cup"),
    (1, "milk", "1/2 cup"),
    (2, "spaghetti pasta", "1 box"),
    (2, "tomato sauce", "2 cups"),
    (2, "onion", "1 diced"),
    (2, "garlic", "2 cloves, minced"),
    (2, "salt", "1 tsp or to taste"),
    (2, "black pepper", "1/2 tsp or to taste"),
    (2, "meat or meat substitute of choice", "1 cup"),
    (3, "bananas", "3 mashed, ripe and browning ones work best"),
    (3, "sugar", "1/3 cup"),
    (3, "gluten-free flour blend", "1 1/2 cups"),
    (3, "plant-based milk of choice", "1/2 cup"),
    (3, "baking powder", "1 tsp"),
    (3, "vanilla extract", "1 tsp"),
    (3, "flax eggs (or normal eggs if not vegan)", "2"),
    (4, "frozen or fresh berries", "2/3 cup"),
    (4, "banana", "1"),
    (4, "milk of choice (plant-based or regular)", "2/3 cup"),
    (5, "chickpeas", "1 can"),
    (5, "tahini", "2 tbs"),
    (5, "olive oil", "1 tbs"),
    (5, "salt", "1 tsp"),
    (5, "olives", "handful, roughly chopped"),
    (6, "Shelled pumpkin seeds", "1 cup"),
    (6, "olive oil", "1 tbs"),
    (6, "salt", "1 tsp"),
    (6, "seasonings of choice", "2 tsp"),
    (7, "oatmeal", "1 cup"),
    (7, "milk, plant-based milk, water", "2 cup"),
    (7, "peanut butter", "2 tbs"),
    (7, "toppings of choice", "any amount that you like"),
    (8, "dried lentils", "1 1/2 cups"),
    (8, "carrots", "3, peeled and chopped"),
    (8, "onion", "1, diced"),
    (8, "garlic", "3 cloves, minced"),
    (8, "Vegetable broth", "4 cups"),
    (8, "salt", "1 tsp, or to taste"),
    (8, "black pepper", "1 tsp, or to taste"),
    (8, "lemon juice", "1 tbsp, or to taste");