INSERT INTO steps (recipeid, text)
VALUES
    (1, 'Pre-heat pan on stove on medium heat'),
    (1, 'Mix dry ingredients together in a bowl'),
    (1, 'Mix wet ingredients together in a bowl'),
    (1, 'Add wet ingredients to dry ingredients and mix until combined'),
    (1, 'lightly oil pan to prevent sticking'),
    (1, 'Add about 1/3 cup of pancake mixture'),
    (1, 'Once you see bubbles start to form, flip pancake and cook for a couple of minutes until the bottom gets golden brown'),
    (1, 'Repeat until all the batter is used up, add whatever topping you like, and enjoy'),
    (2, 'Cook pasta according to package directions and set aside, add oil to prevent sticking'),
    (2, 'Heat pan on stove on medium heat and once heated add olive oil'),
    (2, 'add onions a cook until soft and add garlic and cook an additional two minutes'),
    (2, 'add meat or meat substitute to pan and cook until browning and cooked all the eay through'),
    (2, 'add tomato sauce, salt, and pepper and let cook about 10-15 min'),
    (2, 'add pasta and combine and serve while warm'),
    (3, 'Pre-heat oven to 400 degrees'),
    (3, 'Mix dry ingredients together in a bowl'),
    (3, 'Mix wet ingredients together in a bowl'),
    (3, 'Add wet ingredients to dry ingredients and mix until combined'),
    (3, 'Spray loaf pan with oil to prevent sticking'),
    (3, 'Add mixture to pan and bake for 20min or until top gets golden brown'),
    (3, 'Let cool completely before taking out of the pan'),
    (3, 'Enjoy'),
    (4, 'add all ingredients to the blender'),
    (4, 'blend on high for a couple of minutes until smooth'),
    (4, 'transfer and enjoy'),
    (5, 'add all ingredients, except olives, to food processer'),
    (5, 'blend on high speed until smooth and combined'),
    (5, 'transfer and add olives, and enjoy'),
    (6, 'preheat oven to 375 degrees'),
    (6, 'line a baking sheet with parchment paper'),
    (6, 'add mixture to pan and bake for about 20min'),
    (6, 'let cool, and then enjoy'),
    (7, 'add oatmeal and milk of choice or water to a saucepan and bring to a boil'),
    (7, 'reduce heat to a simmer and cook for a couple of minutes until the oatmeal reaches your desired consistency'),
    (7, 'add in peanut butter and mix'),
    (7, 'transfer to a bowl and add desired toppings'),
    (8, 'heat oil in a pot on medium heat'),
    (8, 'add carrot, onion, and garlic and cook for about 5 minutes or unitl soft'),
    (8, 'add vegetable broth and lentils and bring to a boil'),
    (8, 'once at a boil bring to a simmer and let cook for about 30 min or until the lentils are soft'),
    (8, 'add salt, pepper, and lemon juice and adjust to taste, and serve hot');

